
# staged.dependencies config file
# put absolute paths for the directory!
# cp inst/config.yaml ~/.staged.dependencies/

---

local_packages:
#- repo: openpharma/stageddeps.house
#  host: https://github.com
#  directory: "/Users/<USERNAME>/Desktop/ClonedRepos/NESTprojects/stageddeps_test/stageddeps.house"
